name: fweaking-auto-checkout
on: [push]
jobs:
  fweaking-checkout:
    runs-on: ubuntu-latest #replace later with local runner
    steps:
      - name: "fweaking checkout main docsite"
        uses: actions/checkout@v5
        with:
          repository: purpletiger808/docsite
          token: ${{  secrets.FWEAKING_TOKEN  }}
          path: NOTdocsite
          
      - name: "get the fweaking actual docs"
        uses: actions/checkout@v5
        with:
          path: main

      - name: "fweaking combines them"
        run: |
          rm -rf docsite/docs
          mkdir docsite/docs
          cp main/*.md docsite/docs
          cd docsite/docsite

      - name: "fweaking build"
        run: | 
          ls -a
          npm run build

      - name: "fweaking precompress"
        run: |
          tar -zcf .tar.gz docsite/build
        
      - name: "fweaking upload artifact"
        uses: actions/upload-artifact@v5.0.0
        with:
          name: "fweaking-build-artifact"
          path: /docsite/build
          if-no-files-found: error
          compression-level: 6
