name: auto-checkout
on: [push]
jobs:
  checkout:
    runs-on: ubuntu-latest #replace later with local runner
    steps:
      - name: "checkout main docsite"
        uses: actions/checkout@v5
        with:
          repository: purpletiger808/docsite
          token: ${{  secrets.FWEAKING_TOKEN  }}
          
      - name: "get the actual docs"
        uses: actions/checkout@v5
        with:
          path: ./docs
          
      - name: "test checkouts"  
        run: |
          ls -a

      - name: "get the packages"
        run: |
          npm install
          
      - name: "build"
        run: | 
          npm run build

      - name: "precompress"
        run: |
          ls -a
          tar -zcf buildfact.tar.gz build
        
      - name: "upload artifact"
        uses: actions/upload-artifact@v5.0.0
        with:
          name: "build-artifact"
          path: ./build
          if-no-files-found: error
          compression-level: 6
